from __future__ import annotations

from typing import Protocol

from corectx.schemas import MemoryAtom, RawEvent, SourceSpan


class MemoryStore(Protocol):
    def add(self, atom: MemoryAtom) -> None: ...

    def list(self) -> list[MemoryAtom]: ...

    def get(self, atom_id: str) -> MemoryAtom | None: ...


class EvidenceStore(Protocol):
    def add(self, span: SourceSpan) -> None: ...

    def recover(self, event_id: str) -> list[SourceSpan]: ...


class MemoryBackend(Protocol):
    def put_event(self, event: RawEvent) -> None: ...

    def put_atom(self, atom: MemoryAtom) -> None: ...

    def get_atom(self, atom_id: str) -> MemoryAtom | None: ...

    def search_atoms(self, query: str, *, limit: int = 5) -> list[MemoryAtom]: ...

    def get_sources(self, source_id: str) -> list[SourceSpan]: ...

    def get_related(self, atom_id: str, *, limit: int = 5) -> list[MemoryAtom]: ...

    def update_atom(self, atom: MemoryAtom) -> None: ...

    def mark_superseded(self, atom_id: str, superseded_by: str) -> None: ...

    def quarantine_atom(self, atom_id: str, reason: str) -> None: ...

    def rollback_atom(self, atom_id: str) -> bool: ...
